# Generated by Django 4.2.7 on 2026-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('atomic_number', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('atomic_mass', models.FloatField(blank=True, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=1, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#E0E0E0', max_length=7)),
                ('protons', models.IntegerField(blank=True, null=True)),
                ('neutrons', models.IntegerField(blank=True, null=True)),
                ('electrons', models.IntegerField(blank=True, null=True)),
                ('isotopes', models.JSONField(blank=True, default=list)),
                ('electron_configuration', models.CharField(blank=True, max_length=200, null=True)),
                ('valence_electrons', models.IntegerField(blank=True, null=True)),
                ('oxidation_states', models.JSONField(blank=True, default=list)),
                ('ionization_energy', models.FloatField(blank=True, null=True)),
                ('electron_affinity', models.FloatField(blank=True, null=True)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('atomic_radius', models.FloatField(blank=True, null=True)),
                ('ionic_radius', models.FloatField(blank=True, null=True)),
                ('shielding_effect', models.CharField(blank=True, max_length=20, null=True)),
                ('state_at_room_temp', models.CharField(blank=True, max_length=20, null=True)),
                ('color_appearance', models.CharField(blank=True, max_length=100, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('melting_point', models.FloatField(blank=True, null=True)),
                ('boiling_point', models.FloatField(blank=True, null=True)),
                ('electrical_conductivity', models.CharField(blank=True, max_length=20, null=True)),
                ('thermal_conductivity', models.CharField(blank=True, max_length=20, null=True)),
                ('hardness', models.CharField(blank=True, max_length=50, null=True)),
                ('malleability', models.BooleanField(blank=True, null=True)),
                ('ductility', models.BooleanField(blank=True, null=True)),
                ('magnetic_properties', models.CharField(blank=True, max_length=50, null=True)),
                ('reactivity', models.CharField(blank=True, max_length=50, null=True)),
                ('bond_types', models.JSONField(blank=True, default=list)),
                ('acidity_basicity', models.CharField(blank=True, max_length=50, null=True)),
                ('corrosion_behavior', models.CharField(blank=True, max_length=200, null=True)),
                ('combustion_behavior', models.CharField(blank=True, max_length=200, null=True)),
                ('radioactivity', models.CharField(blank=True, max_length=50, null=True)),
                ('half_life', models.CharField(blank=True, max_length=100, null=True)),
                ('nuclear_spin', models.CharField(blank=True, max_length=20, null=True)),
                ('crystal_structure', models.CharField(blank=True, max_length=50, null=True)),
                ('lattice_parameters', models.CharField(blank=True, max_length=200, null=True)),
                ('coordination_number', models.IntegerField(blank=True, null=True)),
                ('enthalpy_formation', models.FloatField(blank=True, null=True)),
                ('entropy', models.FloatField(blank=True, null=True)),
                ('heat_capacity', models.FloatField(blank=True, null=True)),
                ('emission_spectrum', models.CharField(blank=True, max_length=200, null=True)),
                ('refractive_index', models.FloatField(blank=True, null=True)),
                ('biological_role', models.CharField(blank=True, max_length=50, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=50, null=True)),
                ('abundance', models.CharField(blank=True, max_length=200, null=True)),
                ('natural_or_synthetic', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['atomic_number'],
            },
        ),
    ]
